name: Publish oidc-authservice image

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: arrikto/oidc-authservice
          path: oidc-authservice
      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: zjuici/mirror.arrikto.oidc-authservice
          # TODO: it's difficult to get the sha for a checkout action now
          # See <https://github.com/actions/checkout/issues/209>
          tags: |
            # use custom value instead of git tag
            type=raw,value=0c4ea9a
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          file: oidc-authservice/Dockerfile
          context: oidc-authservice
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
